"use client";

import LegalShell, { LegalSection } from "../legal-shell";
import { useLocale, useT } from "../i18n/context";
import { SITE } from "../site-config";

type Section = {
  title: string;
  paragraphs?: string[];
  list?: string[];
};

const CONTENT: Record<"en" | "zh", { title: string; sections: Section[] }> = {
  en: {
    title: "Terms of Service",
    sections: [
      {
        title: "1. Accepting the Terms",
        paragraphs: [
          `Welcome to ${SITE.brandEn} ("the Service"). By registering or using the Service, you confirm that you have read, understood, and agree to be bound by these Terms of Service. If you do not agree to any term, please stop using the Service.`,
        ],
      },
      {
        title: "2. Service Description",
        paragraphs: ["The Service provides the following features:"],
        list: [
          "AI destiny consultation: Liu Yao, Plum Blossom, and Qi Men Dun Jia chart casting with AI readings.",
          "AI chat: credit-based general AI conversation.",
          "Credits system: account credit management, recharge, and usage records.",
        ],
      },
      {
        title: "3. Account Registration",
        list: [
          "You must provide a valid email address at registration.",
          "You are responsible for keeping your account and password safe; losses caused by poor safekeeping are yours to bear.",
          "Accounts may not be transferred or lent to others.",
        ],
      },
      {
        title: "4. Credits & Recharge",
        list: [
          "Credits are a virtual benefit within the Service; they are not currency, a financial product, or an investment.",
          "Credits are deducted per use: each AI reading costs 5 credits, subject to the published rate on the page.",
          "Recharge amounts and credited credits follow the published plans; prices may change, but changes do not affect already-purchased credits.",
          "Unless required by law, recharged credits are generally non-refundable.",
          "Credits have no expiry, but we may reclaim credits or freeze accounts that are inactive for a long time or violate these Terms.",
        ],
      },
      {
        title: "5. Acceptable Use",
        paragraphs: ["When using the Service, you agree not to:"],
        list: [
          "Use the Service for illegal, infringing, or rights-harming activities.",
          "Use automated means (scripts, crawlers, etc.) to batch-call, scrape data, or disrupt the Service.",
          "Reverse engineer, decompile, or attempt to obtain the source code of the Service.",
          "Distribute false, harmful, threatening, insulting, or defamatory content.",
          "Impersonate others or provide false information.",
        ],
      },
      {
        title: "6. Destiny Consultation Disclaimer",
        paragraphs: ["This is an important disclaimer; please read carefully:"],
        list: [
          "AI destiny consultation (Liu Yao, Plum Blossom, Qi Men Dun Jia) and AI chat content is provided for cultural study, entertainment, and reference only.",
          "Such content does not constitute medical, legal, financial, investment, psychological, or other professional advice, nor does it predict or guarantee future events.",
          "Consultation results are generated by algorithms and AI models and may be biased or inaccurate. We make no express or implied warranty as to their accuracy or completeness.",
          "You should make decisions based on your own judgment and bear responsibility for any actions taken based on the Service content.",
          "For important decisions (medical, investment, legal), please consult a licensed professional; do not rely on this Service.",
        ],
      },
      {
        title: "7. Intellectual Property",
        paragraphs: [
          `The interface, copy, algorithms, and design of the Service are owned by ${SITE.brandEn}. Unauthorized reproduction, distribution, or commercial use is prohibited. Content you generate using the Service may be used personally within reasonable limits, but may not be resold commercially.`,
        ],
      },
      {
        title: "8. Service Changes & Interruption",
        paragraphs: [
          "We may change, suspend, or terminate all or part of the Service at any time, and will try to notify in advance. We are not liable for losses caused by service interruptions due to maintenance, failure, or force majeure.",
        ],
      },
      {
        title: "9. Account Termination",
        paragraphs: [
          "If you violate these Terms, we may — depending on severity — warn you, suspend the Service, freeze credits, or terminate your account, without liability.",
        ],
      },
      {
        title: "10. Disclaimer & Limitation of Liability",
        paragraphs: [
          'The Service is provided on an "as is and as available" basis.',
          "To the maximum extent permitted by law, we are not liable for any direct, indirect, incidental, or consequential losses arising from using or being unable to use the Service.",
        ],
      },
      {
        title: "11. Changes to the Terms",
        paragraphs: [
          "We may revise these Terms. Updates will be posted on this page with a revised effective date. Continued use of the Service constitutes acceptance of the revised Terms.",
        ],
      },
      {
        title: "12. Contact Us",
        paragraphs: [`For any questions about these Terms, contact: ${SITE.contactEmail}`],
      },
    ],
  },
  zh: {
    title: "服务条款",
    sections: [
      {
        title: "一、接受条款",
        paragraphs: [
          `欢迎使用 ${SITE.brand}（以下简称“本服务”）。注册或使用本服务即表示你已阅读、理解并同意受本服务条款约束。如不同意任一条款，请停止使用。`,
        ],
      },
      {
        title: "二、服务说明",
        paragraphs: ["本服务提供以下功能："],
        list: [
          "AI 命理咨询：六爻、梅花易数、奇门遁甲三类排盘与 AI 卦象解读。",
          "AI 对话：基于积分的通用 AI 聊天。",
          "积分系统：账户积分管理、充值与使用记录。",
        ],
      },
      {
        title: "三、账户注册",
        list: [
          "注册须提供真实有效的邮箱地址。",
          "你须妥善保管账号与密码，因账户保管不善造成的损失由你自行承担。",
          "每人均不得转让、出借账号。",
        ],
      },
      {
        title: "四、积分与充值",
        list: [
          "积分是本服务内的虚拟权益，不构成货币、金融产品或任何投资。",
          "积分按次扣减：AI 卦象解读每次扣 5 积分，具体以页面公示为准。",
          "充值金额与到账积分以充值页面公示为准；价格可能调整，调整不影响已购买的积分。",
          "除法律另有规定外，已充值积分一般不予退款。",
          "积分长期有效，但如账户长期未登录或违反本条款，我们有权回收积分或冻结账户。",
        ],
      },
      {
        title: "五、使用规范",
        paragraphs: ["使用本服务时，你承诺不得："],
        list: [
          "利用服务从事违法、侵权或损害他人权益的活动。",
          "以自动化手段（脚本、爬虫等）批量调用、抓取数据或干扰服务。",
          "对服务进行逆向工程、反编译或试图获取源代码。",
          "传播虚假、有害、胁迫、侮辱、诽谤等内容。",
          "冒充他人或提供虚假信息。",
        ],
      },
      {
        title: "六、命理咨询免责声明",
        paragraphs: ["本条为重要免责条款，请仔细阅读："],
        list: [
          "本服务提供的 AI 命理咨询（六爻、梅花易数、奇门遁甲）及 AI 对话内容，仅供文化研究、娱乐与参考之用。",
          "上述内容不构成医疗、法律、金融、投资、心理或其他专业建议，亦不构成对未来事件的预测或保证。",
          "咨询结果由算法与 AI 模型生成，可能存在偏差或不准确，我们不对其准确性、完整性作任何明示或暗示的保证。",
          "你应基于自身判断做出决定，并对自己基于服务内容采取的任何行为及其后果自行承担责任。",
          "重要决策（如医疗、投资、法律事务）请咨询持牌专业人士，切勿依赖本服务。",
        ],
      },
      {
        title: "七、知识产权",
        paragraphs: [
          `本服务的界面、文案、算法、设计等知识产权归 ${SITE.brand} 所有，未经授权不得复制、传播或商用。你使用本服务生成的内容，可在合理范围内自用，但不得用于商业转售。`,
        ],
      },
      {
        title: "八、服务变更与中断",
        paragraphs: [
          "我们可能随时变更、暂停或终止全部或部分服务，并尽力提前通知。因系统维护、故障或不可抗力导致服务中断，我们不承担因此造成的损失。",
        ],
      },
      {
        title: "九、账户终止",
        paragraphs: [
          "如你违反本条款，我们有权视情节轻重采取警告、暂停服务、冻结积分或终止账户等措施，且不承担赔偿责任。",
        ],
      },
      {
        title: "十、免责与责任限制",
        paragraphs: [
          '本服务按"现状"和"可用"状态提供。',
          "在法律允许的最大范围内，对于因使用或无法使用本服务而产生的任何直接、间接、附带或后果性损失，我们不承担责任。",
        ],
      },
      {
        title: "十一、条款变更",
        paragraphs: [
          "我们可能修订本服务条款，更新后在本页公示并修订生效日期。继续使用服务即视为你接受修订后的条款。",
        ],
      },
      {
        title: "十二、联系我们",
        paragraphs: [`如有任何关于本条款的问题，请联系：${SITE.contactEmail}`],
      },
    ],
  },
};

export default function TermsView() {
  const { locale } = useLocale();
  const t = useT();
  const c = CONTENT[locale];
  return (
    <LegalShell>
      <h1 className="mb-2 text-2xl font-bold">{c.title}</h1>
      <p className="mb-8 text-sm text-gray-500">
        {t("legal.effective")}
        {SITE.effectiveDate}
      </p>

      {c.sections.map((s, i) => (
        <LegalSection
          key={i}
          title={s.title}
          paragraphs={s.paragraphs}
          list={s.list}
        />
      ))}
    </LegalShell>
  );
}
